language: node_js
node_js:
  - 4.2.4
branches:
  only:
    - master
before_install:
  git clone https://github.com/aoh/radamsa.git && cd radamsa && make && sudo make install && exit
script:
  npm test
